ACTION_TYPE_CLUE = "clue"
ACTION_TYPE_CARD_IDENTITY = "cardIdentity"
ACTION_TYPE_DISCARD = "discard"
ACTION_TYPE_DRAW = "draw"
ACTION_TYPE_GAME_OVER = "gameOver"
ACTION_TYPE_PLAY = "play"
ACTION_TYPE_PLAYER_TIMES = "playerTimes"
ACTION_TYPE_STRIKE = "strike"
ACTION_TYPE_STATUS = "status"
ACTION_TYPE_TURN = "turn"

COMMAND_ACTION_TYPE_PLAY = 0
COMMAND_ACTION_TYPE_DISCARD = 1
COMMAND_ACTION_TYPE_COLOR_CLUE = 2
COMMAND_ACTION_TYPE_RANK_CLUE = 3
COMMAND_ACTION_TYPE_END_GAME = 4
COMMAND_ACTION_TYPE_END_GAME_BY_VOTE = 5
